[project]
name = "chatgpt-automation"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
    "psutil>=7.0.0",
    "selenium>=4.33.0",
    "webdriver-manager>=4.0.2",
]
